language: node_js
node_js:
  - "node"
  - "8"
services:
  - mongodb
install:
  - npm install
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh deploy.sh
  on:
    branch: master
script:
  - npm test